### ISSUE TITLE
Allow scrolling

### ISSUE THREAD

**Issue by lucasrodwell** [MSzturc/obsidian-advanced-slides#230]
I often want to interactively add to presentations with my audience, which means that I cannot be sure not to overflow on a slide, and need to be able to scroll. Sometimes I have longer texts that I don't want to split up either, such as embeds, where it would be very helpful to be able to scroll.

I have tried solving this with css snippets, but [this](https://www.analysisman.com/2022/01/obsidian-css-presentation.html) solution doesn't work, as with advanced slides there is a problem with long texts being clipped above the presentation grid when using overflow-y. I think [this](https://stackoverflow.com/questions/49278725/centered-elements-inside-a-flex-container-are-growing-and-overflowing-beyond-top) is the reason.

I have tried to adapt the css to no avail. If it is not possible for a css snippet solution, a toggle to allow scrolling would be of great help to me.

**Comment by damywise** [comment]
I added this at the end of scrollable.css:
```css
.present > div,
.past > div,
.future > div
{
    display: block !important;
}
```
It works, at the very least.

**Comment by damywise** [comment]
Ah, also you might want to remove 
```css
    overflow: auto !important;
```
from scrollable.css, that makes it scrollable horizontally which shouldn't be

**Comment by lucasrodwell** [comment]
Is your scrollable.css from [here](https://github.com/MSzturc/obsidian-advanced-slides/issues/66)?

**Comment by damywise** [comment]
Ah yes it is correct. Sorry about that, I forgot to mention it.

**Comment by lucasrodwell** [comment]
Unfortunately, I can't get it to work... To double-check, the whole snippet is the following ???

```css
.reveal:not(.overview) .slides {
    overflow-x: hidden !important;
    overflow-y: auto !important;
    pointer-events: auto !important;
}

.reveal:not(.overview) .slides::-webkit-scrollbar {
    display: none;
}

.reveal:not(.overview) .slides .past, .reveal:not(.overview) .slides .future {
    height: 0;
}

.present > div,
.past > div,
.future > div
{
    display: block !important;
}
```
